### ISSUE TITLE
Referencing latest `resource.yaml` fails to download

### ISSUE THREAD

**Issue by DrkCloudStrife** [razee-io/Razeedash-api#1330]
The last two release tags

*  [1.5.0](https://github.com/razee-io/Razeedash-api/releases/tag/1.5.0)
*  [2.0.0](https://github.com/razee-io/Razeedash-api/releases/tag/2.0.0)
 
don't have the `resource.yaml` file included which causes the retrieval of it to fail.

This happens when calling it directly via `https://github.com/razee-io/Razeedash-api/releases/latest/download/resource.yaml` or through `Razee` git repo references, e.g.

* https://github.com/razee-io/Razee/blob/d882e3d146f5008ea5d354eb68c4272e58a475ff/kubernetes/Razee/razeedash.yaml#L22
* https://github.com/razee-io/Razee/blob/d882e3d146f5008ea5d354eb68c4272e58a475ff/kubernetes/Razee/razeedash-all-in-one.yaml#L112

**Comment by kdai7** [comment]
problem was with the github token. Newest release has resource.yaml asset included https://github.com/razee-io/Razeedash-api/releases/tag/2.0.4
