### ISSUE TITLE
subscriptionsByTag datahook is missing orgId

### ISSUE THREAD

**Issue by crhuff-ibm** [razee-io/Razeedash-api#439]
The schema indicates no `orgId` to be passed to `subscriptionsByTag` but fails when provided a string of tags. Also, is tag supposed to be the label name, or label uuid (or both?)
Example
```
{
    subscriptionsByTag(
        tags: "abc"
    ) { subscription_uuid }
}
```
`{
  "errors": [
    {
      "message": "org id was not found",
...
`

**Comment by crhuff-ibm** [comment]
@yingwang-us @rmgraham

**Comment by nathanleviere** [comment]
subscriptionsByTag is no longer supported and is removed
