### ISSUE TITLE
Subscriptions by cluster

### ISSUE THREAD

**Issue by crhuff-ibm** [razee-io/Razeedash-api#498]
Need a way to return subscriptions by cluster (no subscriptions object is returned from clusterByClusterId)

**Comment by rmgraham** [comment]
I'm working on this one currently. Theres not a direct correlation from cluster -> subs. Its actually cluster->groups->subs. So would this output format be sufficient?:
```
query clustersByOrgId($orgId:String!) {
  clustersByOrgId(orgId:$orgId){
    id
    orgId
    created
    updated
    groupObjs{
        uuid
        name
        subscriptions{
            uuid
            name
        }
    }
  }
}
```
Its a little messy and might be annoying to parse, but it seems like thats the official graphql way to output it.

**Comment by crhuff-ibm** [comment]
Yeah that should be fine with us
