### ISSUE TITLE
Batch group editing per cluster

### ISSUE THREAD

**Issue by crhuff-ibm** [razee-io/Razeedash-api#500]
`groupClusters` is currently the only way to add a cluster to a group. If multiple groups want to be added to/remove from a cluster we need to iterate. It'd be nice if we could have something like `assignGroups` `unassignGroups` or just `editClusterGroups`

**Comment by rmgraham** [comment]
https://github.com/razee-io/Razeedash-api/pull/525

Lets you do:
```
mutation assignClusterGroups($orgId:String!, $groupUuids: [String!]!, $clusterIds: [String!]!) {
  assignClusterGroups(orgId:$orgId, groupUuids:$groupUuids, clusterIds:$clusterIds){
    modified
  }
}
```
```
{
	"orgId": "{{ org_id  }}",
	"groupUuids": [
		"af8a23b4-f027-40c4-8c3e-54c1b2ec94c5",
		"f5203044-f442-4bca-b824-177bc8a39656"
	],
	"clusterIds": [
		"25389434-7da4-46b2-a9e9-d38f1e2f0faf"
	]
}
```

and same with unassign. Both support any number of groupUuids and any number of clusterIds

**Comment by rmgraham** [comment]
Also needs editGroups(clusterId, groupUuids), which overwrites the list of groups for a single cluster

**Comment by rmgraham** [comment]
https://github.com/razee-io/Razeedash-api/pull/549
signature is `editClusterGroups(orgId: String!, clusterId: String!, groupUuids: [String!]!)`
