### ISSUE TITLE
Return version content from subscription

### ISSUE THREAD

**Issue by crhuff-ibm** [razee-io/Razeedash-api#555]
`subscription` returns `version: String!` and `versionUuid: String!`, return `versionObject: Version!` additionally so we dont have to perform an additional fetch for version content/description.

**Comment by rmgraham** [comment]
We wont be able to implement this due to how much processing it would require to load all the resource contents off of s3. Does the UI require loading multiple resources at once?

**Comment by crhuff-ibm** [comment]
I think we're able to ignore this one.
