### ISSUE TITLE
Incorrect URL for RAZEEDASH in watch-keeper config map

### ISSUE THREAD

**Issue by padraic-edwards** [razee-io/Razeedash-api#65]
After installing Razee my cluster did not appear in `app.razee.io` dashboard. I had to go in and update the `watch-keeper-config` config map and restart the pod.

I changed 
    "RAZEEDASH_URL": "http://app.razee.io/api/v2"
to
    "RAZEEDASH_URL": "https://app.razee.io/api/v2"

**Comment by mckaymic** [comment]
This was just fixed in the latest release.  We were not picking up the correct URL protocol from the proxy.  Let us know if you still have issues.

Thanks!
