### ISSUE TITLE
"Maximum call stack size exceeded" error on addChannelVersion yaml file upload 

### ISSUE THREAD

**Issue by rmgraham** [razee-io/Razeedash-api#722]
error:
`
{"errors":[{"message":"Provided YAML content is not valid: RangeError: Maximum call stack size exceeded","locations":[{"line":2,"column":3}],"path":["addChannelVersion"],"extensions":{"incidentID":"69524c53-4340-4f96-a493-667d87129228","code":"ValidationError","exception":{"incidentID":"69524c53-4340-4f96-a493-667d87129228"}}}],"data":null,"extensions":{"tracing":{"version":1,"startTime":"2020-11-09T19:45:49.456Z","endTime":"2020-11-09T19:45:49.713Z","duration":257783047,"execution":{"resolvers":[{"path":["addChannelVersion"],"parentType":"Mutation","fieldName":"addChannelVersion","returnType":"AddChannelVersionReply!","startOffset":1373192,"duration":253355597}]}}}}
`

graphql request:
```
              response=$(curl --silent --fail -k --url https://domain.com/graphql \
                  --header 'content-type: multipart/form-data' \
                  --header "Authorization: Bearer ${token}" \
                  --form 'operations={
                  "query": "mutation addChannelVersion($orgId:String!, $channelUuid:String!, $name:String!, $type:String!, $file:Upload, $content:String, $description:String) {\n  addChannelVersion(orgId:$orgId,channelUuid:$channelUuid, name:$name, type:$type, file:$file, content:$content, description:$description){\n    success\n    versionUuid\n  }\n}",
                  "variables": {
                  "orgId": "'${org_id}'",
                  "channelUuid": "'${channel_uuid}'",
                  "name": "'${deployment_file_regional_name}'",
                  "type": "application/yaml",
                  "file": null,
                  "content": null,
                  "description": null
                  },
                  "operationName": "addChannelVersion"
              }' \
                  --form 'map={"localfile":["variables.file"]}' \
                  --form localfile=@${resource})
```

We're probably doing something wrong with file streams, since sending direct content seems to work.

**Comment by david-shepard** [comment]
Might be related to https://stackoverflow.com/questions/59620803/createreadstream-throwing-rangeerror-maximum-call-stack-size-exceeded-when-up

**Comment by david-shepard** [comment]
Here's your relevant code snippet https://github.com/razee-io/Razeedash-api/blob/master/app/apollo/resolvers/channel.js#L271
