### ISSUE TITLE
Add Timestamp to razeedploy install job name

### ISSUE THREAD

**Issue by alewitt2** [razee-io/Razeedash-api#784]
When a user attaches a cluster to their org, they get a kubectl command to run, which will apply a kubernetes job to the cluster. This job then installs the necessary razeedeploy components on the cluster. If the user ever wants to re-run this kubectl command that we give them, today that would have to delete the job they originally applied before applying the new one.

To avoid confusion around this, we should append a timestamp to the name of the job, so everytime a user applies a new kubectl command, it will have a "new" name and not throw any errors.

The job is fetched (generated from [this repo](https://github.com/razee-io/razeedeploy-delta/blob/master/kubernetes/job/resource.yaml)) and rendered here https://github.com/razee-io/Razeedash-api/blob/e7528f5bddd5a2dc07b196485fdda83ef51c33aa/app/routes/install/index.js#L69-L82

all we need to do is add `UUID` to the `view`, where UUID has a value of `the number of milliseconds elapsed since January 1, 1970 00:00:00 UTC`, and it needs to be prefixed with a `-`.

ex:
the template will look like 
```
"razeedeploy-job{{{ UUID }}"
```

so if UUID = "-1613666791168"

then the final yaml should show
```
"razeedeploy-job-1613666791168"
```

**Comment by adamkingit** [comment]
Complete
