### ISSUE TITLE
'ChannelByName' and 'ChannelVersion' queries giving different channel name for a single configuration after renaming configuration

### ISSUE THREAD

**Issue by mssachan** [razee-io/Razeedash-api#828]
We renamed one configuration from `local-file-1_new` to `local-file01`.

After that we executed below two GraphQL queries.

**`ChannelByName` query response:**

`{"level":"info","ts":"2021-03-19T10:49:18.334Z","caller":"operations/satellite_storage.go:878","msg":"Exit GetConfigurationVersionByName()","req-id":"1d8f4c15-24ea-4716-845e-0c4a5b946ed1","response":{"name":"local-file01","uuid":"5148b847-fe10-4b85-8418-5a37313cbfc2","orgId":"3188cce343eee2b70414f020e28f751a","created":"2021-03-18T18:41:00.738Z","versions":[{"uuid":"bcdd9430-6b7e-4c46-92d7-f24e288e121c","name":"local-file01","description":"local-file01","location":"s3"}],"subscriptions":[]}}`

`"name":"local-file01","uuid":"5148b847-fe10-4b85-8418-5a37313cbfc2","orgId":"3188cce343eee2b70414f020e28f751a"`

**`ChannelVersion` query response**

`"level":"info","ts":"2021-03-19T10:49:18.819Z","caller":"operations/satellite_storage.go:960","msg":"Exit GetConfigurationVersionByUUID()","req-id":"1d8f4c15-24ea-4716-845e-0c4a5b946ed1","response":{"name":"local-file01","type":"application/yaml","description":"local-file01","content":"apiVersion: v1\nitems:\n- apiVersion: deploy.razee.io/v1alpha2\n  kind: MustacheTemplate\n  metadata:\n    creationTimestamp: null\n    name: local-file01-new\n  spec:\n    env:\n    - name: label-key\n      valueFrom:\n        configMapKeyRef:\n          key: label-key\n          name: local-file01-new\n    - name: label-value\n      valueFrom:\n        configMapKeyRef:\n          key: label-value\n          name: local-file01-new\n    - name: devicepath?\n      value: \"true\"\n    - name: devicepath\n      valueFrom:\n        configMapKeyRef:\n          key: devicepath\n          name: local-file01-new\n          type: json\n    - name: fstype\n      valueFrom:\n        configMapKeyRef:\n          key: fstype\n          name: local-file01-new\n    - name: storage-template-name\n      value: local-volume-file\n    strTemplates:\n    - |\n      ---\n      apiVersion: v1\n      kind: List\n      metadata:\n          name: local-volume-file\n          namespace: kube-system\n          annotations:\n              version: local-volume-file-45\n      items:\n          - apiVersion: v1\n            kind: Namespace\n            metadata:\n                name: local-storage\n          - apiVersion: operators.coreos.com/v1alpha2\n            kind: OperatorGroup\n            metadata:\n                name: local-operator-group\n                namespace: local-storage\n            spec:\n                targetNamespaces:\n                    - local-storage\n          - apiVersion: operators.coreos.com/v1alpha1\n            kind: Subscription\n            metadata:\n                name: local-storage-operator\n                namespace: local-storage\n            spec:\n                channel: \"4.6\"\n                installPlanApproval: Automatic\n                name: local-storage-operator\n                source: redhat-operators\n                sourceNamespace: openshift-marketplace\n          - apiVersion: local.storage.openshift.io/v1\n            kind: LocalVolume\n            metadata:\n                name: local-disk\n                namespace: local-storage\n            spec:\n                nodeSelector:\n                    nodeSelectorTerms:\n                        - matchExpressions:\n                              - key: \"{{ label-key }}\"\n                                operator: In\n                                values:\n                                - \"{{ label-value }}\"\n                storageClassDevices:\n                    - storageClassName: \"sat-local-file-gold\"\n                      volumeMode: Filesystem\n                      fsType: \"{{ fstype }}\"\n                      devicePaths:\n                        {{#devicepath}}\n                        - \"{{{ item }}}\"\n                        {{/devicepath}}\n- apiVersion: v1\n  data:\n    devicepath: '[{\"item\":\"/dev/abc\"},{\"item\":\"/dev/xyz\"}]'\n    fstype: ext4\n    label-key: node\n    label-value: localfile\n    location: sat-prod\n    source-branch: \"\"\n    source-org: \"\"\n    storage-template-name: local-volume-file\n    storage-template-version: \"4.6\"\n  kind: ConfigMap\n  metadata:\n    creationTimestamp: null\n    name: local-file01-new\nkind: List\nmetadata: {}\n","uuid":"bcdd9430-6b7e-4c46-92d7-f24e288e121c","orgId":"3188cce343eee2b70414f020e28f751a","channelId":"5148b847-fe10-4b85-8418-5a37313cbfc2","channelName":"local-file01_new","created":"2021-03-18T18:41:02.215Z"}} `

`"uuid":"bcdd9430-6b7e-4c46-92d7-f24e288e121c","orgId":"3188cce343eee2b70414f020e28f751a","channelId":"5148b847-fe10-4b85-8418-5a37313cbfc2","channelName":"local-file01_new"`

I expected both queries should return same channel name.

**Comment by mssachan** [comment]
**See the response from `Insomnia` tool for `ChannelVersionByName` query** 

<img width="2160" alt="Screenshot 2021-03-24 at 11 51 45 AM" src="https://user-images.githubusercontent.com/34068620/112304047-08423480-8cc3-11eb-924b-45816f35991c.png">



**For `Channels` query**

<img width="2160" alt="Screenshot 2021-03-24 at 11 55 42 AM" src="https://user-images.githubusercontent.com/34068620/112304095-17c17d80-8cc3-11eb-9a5f-2fef0519d8a7.png">

**Comment by tasneem067** [comment]
#856
