### ISSUE TITLE
Enhance apollo logging to capture the GraphQL query without exposing the contents

### ISSUE THREAD

**Issue by adamkingit** [razee-io/Razeedash-api#835]
The [bunyan config](https://github.com/razee-io/Razeedash-api/blob/master/app/apollo/utils/bunyan.js#L39-L55) for the api 
https://github.com/razee-io/Razeedash-api/blob/master/app/apollo/utils/bunyan.js#L39-L55 excludes the body to avoid logging configuration or resources, but in doing so misses logging the GraphQL query which is sometimes necessary to understand what is going on. Enhace the logging to capture the query while avoiding capturing any potentially sensitive data.

Resources that might be helpful:
- https://www.npmjs.com/package/express-bunyan-logger#configuration
- https://www.apollographql.com/docs/apollo-server/monitoring/metrics/#logging
- https://stackoverflow.com/questions/54273194/log-apollo-server-graphql-query-and-variables-per-request

**Comment by tasneem067** [comment]
#850
